### ISSUE TITLE
[Feature Request] Debug checkbox!

### ISSUE THREAD

**Issue by toyxyz** [sdbds/magic-animate-for-windows#12]
How about adding a debug checkbox like in this pull request to save only the resulting video, excluding the reference image and densepose footage? 

https://github.com/magic-research/magic-animate/pull/28

![image](https://github.com/sdbds/magic-animate-for-windows/assets/8006000/9c785fcc-c138-4a17-9f0d-55076feb198c)

**Comment by sdbds** [comment]
I will add it after i go home.

**Comment by sdbds** [comment]
I update this now.
