### ISSUE TITLE
at the end of installation, get this error messages

### ISSUE THREAD

**Issue by xiohulp** [sdbds/magic-animate-for-windows#18]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-video.txt'

**Comment by sdbds** [comment]
use git clone --recurse-submodules https://github.com/sdbds/magic-animate-for-windows/
to git pull submodules
