### ISSUE TITLE
生成的速度太慢了

### ISSUE THREAD

**Issue by qzztf** [sdbds/magic-animate-for-windows#19]
显卡是Gtx3060, 12GB显存，使用提供的demo。
如下图所示。
![image](https://github.com/sdbds/magic-animate-for-windows/assets/2748627/fcfd13b6-2b13-4878-a86a-95a07c81a683)
速度如下：
![image](https://github.com/sdbds/magic-animate-for-windows/assets/2748627/382a7413-64ae-44b9-b039-e930e641fff3)
请问是我显卡不行吗？不至于这么慢吧。

**Comment by sdbds** [comment]
确实这么慢，因为是批量生成，参考animatediff+controlnet的生成速度
