### ISSUE TITLE
Getting same result when using original 1.5 model and other 1.5 based model

### ISSUE THREAD

**Issue by Chocobi-1129** [sdbds/magic-animate-for-windows#8]
I got same result when i tried to use other model from civitai. i modified the pretrained model path to downloaded .safetensor file. did i miss anything? 
Also is there's anything i can help with?

**Comment by sdbds** [comment]
plz give the config about your model path

**Comment by FurkanGozukara** [comment]
> plz give the config about your model path


pretrained_model_path: "magicanimate/pretrained_models/Realistic_Vision_V6.0_NV_B1.safetensors"
pretrained_vae_path: "magicanimate/pretrained_models/sd-vae-ft-mse"
pretrained_controlnet_path: "magicanimate/pretrained_models/MagicAnimate/densepose_controlnet"
pretrained_appearance_encoder_path: "magicanimate/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_unet_path: ""

motion_module: "magicanimate/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

source_image:
  - "inputs/applications/source_image/monalisa.png"
  - "inputs/applications/source_image/0002.png"
  - "inputs/applications/source_image/demo4.png"
  - "inputs/applications/source_image/dalle2.jpeg"
  - "inputs/applications/source_image/dalle8.jpeg"
  - "inputs/applications/source_image/multi1_source.png"
video_path:
  - "inputs/applications/driving/densepose/running.mp4"
  - "inputs/applications/driving/densepose/demo4.mp4"
  - "inputs/applications/driving/densepose/demo4.mp4"
  - "inputs/applications/driving/densepose/running2.mp4"
  - "inputs/applications/driving/densepose/dancing2.mp4"
  - "inputs/applications/driving/densepose/multi_dancing.mp4"

inference_config: "configs/inference/inference.yaml"
size: 512
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

**Comment by sdbds** [comment]
> > plz give the config about your model path
> 
> ```
> pretrained_model_path: "magicanimate/pretrained_models/Realistic_Vision_V6.0_NV_B1.safetensors"
> pretrained_vae_path: "magicanimate/pretrained_models/sd-vae-ft-mse"
> pretrained_controlnet_path: "magicanimate/pretrained_models/MagicAnimate/densepose_controlnet"
> pretrained_appearance_encoder_path: "magicanimate/pretrained_models/MagicAnimate/appearance_encoder"
> pretrained_unet_path: ""
> 
> motion_module: "magicanimate/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"
> 
> savename: null
> 
> fusion_blocks: "midup"
> 
> seed:           [1]
> steps:          25
> guidance_scale: 7.5
> 
> source_image:
>   - "inputs/applications/source_image/monalisa.png"
>   - "inputs/applications/source_image/0002.png"
>   - "inputs/applications/source_image/demo4.png"
>   - "inputs/applications/source_image/dalle2.jpeg"
>   - "inputs/applications/source_image/dalle8.jpeg"
>   - "inputs/applications/source_image/multi1_source.png"
> video_path:
>   - "inputs/applications/driving/densepose/running.mp4"
>   - "inputs/applications/driving/densepose/demo4.mp4"
>   - "inputs/applications/driving/densepose/demo4.mp4"
>   - "inputs/applications/driving/densepose/running2.mp4"
>   - "inputs/applications/driving/densepose/dancing2.mp4"
>   - "inputs/applications/driving/densepose/multi_dancing.mp4"
> 
> inference_config: "configs/inference/inference.yaml"
> size: 512
> L:    16
> S:    1 
> I:    0
> clip: 0
> offset: 0
> max_length: null
> video_type: "condition"
> invert_video: false
> save_individual_videos: false
> ```
> 
> ```
> unet_additional_kwargs:
>   unet_use_cross_frame_attention: false
>   unet_use_temporal_attention: false
>   use_motion_module: true
>   motion_module_resolutions:
>   - 1
>   - 2
>   - 4
>   - 8
>   motion_module_mid_block: false
>   motion_module_decoder_only: false
>   motion_module_type: Vanilla
>   motion_module_kwargs:
>     num_attention_heads: 8
>     num_transformer_block: 1
>     attention_block_types:
>     - Temporal_Self
>     - Temporal_Self
>     temporal_position_encoding: true
>     temporal_position_encoding_max_len: 24
>     temporal_attention_dim_div: 1
> 
> noise_scheduler_kwargs:
>   beta_start: 0.00085
>   beta_end: 0.012
>   beta_schedule: "linear"
> ```

This is the original repository, not my repository. The use of safetensors was added independently of the windows version, the original doesn't support this.

**Comment by FurkanGozukara** [comment]
@sdbs i am using yours 

i merged from yours to mine

https://raw.githubusercontent.com/sdbds/magic-animate-for-windows/main/configs/prompts/animation.yaml

**Comment by sdbds** [comment]
I think it's likely that the results don't look any different because the original reference was weighted too high. 
Actually reading the model itself didn't report any errors or other problems.

**Comment by sdbds** [comment]
I think changing some of the delicate models might make the chipping of the face or hands less...

**Comment by FurkanGozukara** [comment]
@sdbds someone on the official thread said that U-NET from 

motion_module: "magicanimate/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

overwriting the U-NET we load from custom checkpoint

**Comment by sdbds** [comment]
> @sdbds someone on the official thread said that U-NET from
> 
> motion_module: "magicanimate/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"
> 
> overwriting the U-NET we load from custom checkpoint

Actually the custom checkpoint only affects the reference migration of the image, the final generation still relies on the official temporal model, just like animatediff. So it's not a bug, the example I gave is also just able to read anime's images.

**Comment by FurkanGozukara** [comment]
@sdbds do you think output can be improved? because it is really bad. i tried 768x768 and it was even worse

**Comment by sdbds** [comment]
> @sdbds do you think output can be improved? because it is really bad. i tried 768x768 and it was even worse

it bases SD1.5 so 512X512 is best result with offical setting.
if I can split motion module,we can change the MM unet

**Comment by FurkanGozukara** [comment]
> > @sdbds do you think output can be improved? because it is really bad. i tried 768x768 and it was even worse
> 
> it bases SD1.5 so 512X512 is best result with offical setting. if I can split motion module,we can change the MM unet

awesome i hope you can do

**Comment by Chocobi-1129** [comment]
> I think it's likely that the results don't look any different because the original reference was weighted too high. Actually loading the model itself didn't report any errors or other problems.

Tks for replying.
this sounds resonable for me

**Comment by Chocobi-1129** [comment]
not bug
