### ISSUE TITLE
instalation error ( ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by abozahran** [sdbds/magic-animate-for-windows#9]
![image](https://github.com/sdbds/magic-animate-for-windows/assets/107565623/748b56ee-f11e-4e3c-b332-c1cc57dce89d)

**Comment by lonelyman0907** [comment]
download this file and unzip it to the video_controlnet_aux folder
https://github.com/sdbds/video_controlnet_aux/tree/9a86fb8077e0fae573ad5240d615bb0a08765874

**Comment by sdbds** [comment]
use
```git clone --recurse-submodules https://github.com/sdbds/magic-animate-for-windows/```
